#!/bin/bash
# Convert line endings to Unix (LF) in case of Windows-style (CRLF)
#dos2unix "$0"

# Setting the Sign-in timer to 24 hours
git config --global credential.helper 'cache --timeout=86400'

# Add all files in directory
git add .

# Commit files to the local "main" branch
# If the commit fails because nothing changed, the script stops

if git diff-index --quiet HEAD --; then
    echo "No changes to commit"
else
    # Commit files to the local "main" branch
    git commit -m "quickSave"
    if [ $? -ne 0 ]; then
        echo "Error: git commit failed"
        exit 1
    fi
fi

# Push files directly to GitHub
#git push

# Might need to enter User & PAT for first save
#Requirements to run
#sudo apt-get install dos2unix
