#!/bin/bash

# Compile the C++ file using clang++

clang++ -Iinclude src/*.cpp -o build/a.out

# Check if the compilation was successful & Run Program

if [ $? -eq 0 ]; then
    # Run the compiled program
    ./build/a.out
else
    echo "Program Ate shit"  # This runs if clang++ encounters errors
    exit 1
fi